// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cycle_items.sql

package database

import (
	"context"
	"database/sql"
)

const createCycleItem = `-- name: CreateCycleItem :one
INSERT INTO cycle_items (id, cycle_id, subject_id, order_index, planned_duration_minutes)
VALUES (?, ?, ?, ?, ?)
RETURNING id, cycle_id, subject_id, order_index, planned_duration_minutes, created_at, updated_at
`

type CreateCycleItemParams struct {
	ID                     string        `json:"id"`
	CycleID                string        `json:"cycle_id"`
	SubjectID              string        `json:"subject_id"`
	OrderIndex             int64         `json:"order_index"`
	PlannedDurationMinutes sql.NullInt64 `json:"planned_duration_minutes"`
}

func (q *Queries) CreateCycleItem(ctx context.Context, arg CreateCycleItemParams) (CycleItem, error) {
	row := q.db.QueryRowContext(ctx, createCycleItem,
		arg.ID,
		arg.CycleID,
		arg.SubjectID,
		arg.OrderIndex,
		arg.PlannedDurationMinutes,
	)
	var i CycleItem
	err := row.Scan(
		&i.ID,
		&i.CycleID,
		&i.SubjectID,
		&i.OrderIndex,
		&i.PlannedDurationMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCycleItem = `-- name: DeleteCycleItem :exec
DELETE FROM cycle_items
WHERE id = ?
`

func (q *Queries) DeleteCycleItem(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCycleItem, id)
	return err
}

const getCycleItem = `-- name: GetCycleItem :one
SELECT id, cycle_id, subject_id, order_index, planned_duration_minutes, created_at, updated_at FROM cycle_items
WHERE id = ?
`

func (q *Queries) GetCycleItem(ctx context.Context, id string) (CycleItem, error) {
	row := q.db.QueryRowContext(ctx, getCycleItem, id)
	var i CycleItem
	err := row.Scan(
		&i.ID,
		&i.CycleID,
		&i.SubjectID,
		&i.OrderIndex,
		&i.PlannedDurationMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCycleItems = `-- name: ListCycleItems :many
SELECT id, cycle_id, subject_id, order_index, planned_duration_minutes, created_at, updated_at FROM cycle_items
WHERE cycle_id = ?
ORDER BY order_index
`

func (q *Queries) ListCycleItems(ctx context.Context, cycleID string) ([]CycleItem, error) {
	rows, err := q.db.QueryContext(ctx, listCycleItems, cycleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CycleItem
	for rows.Next() {
		var i CycleItem
		if err := rows.Scan(
			&i.ID,
			&i.CycleID,
			&i.SubjectID,
			&i.OrderIndex,
			&i.PlannedDurationMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCycleItem = `-- name: UpdateCycleItem :exec
UPDATE cycle_items
SET subject_id = ?, order_index = ?, planned_duration_minutes = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateCycleItemParams struct {
	SubjectID              string        `json:"subject_id"`
	OrderIndex             int64         `json:"order_index"`
	PlannedDurationMinutes sql.NullInt64 `json:"planned_duration_minutes"`
	ID                     string        `json:"id"`
}

func (q *Queries) UpdateCycleItem(ctx context.Context, arg UpdateCycleItemParams) error {
	_, err := q.db.ExecContext(ctx, updateCycleItem,
		arg.SubjectID,
		arg.OrderIndex,
		arg.PlannedDurationMinutes,
		arg.ID,
	)
	return err
}
