// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exercise_logs.sql

package database

import (
	"context"
	"database/sql"
)

const createExerciseLog = `-- name: CreateExerciseLog :one
INSERT INTO exercise_logs (id, session_id, subject_id, topic_id, questions_count, correct_count)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, session_id, subject_id, topic_id, questions_count, correct_count, created_at
`

type CreateExerciseLogParams struct {
	ID             string         `json:"id"`
	SessionID      sql.NullString `json:"session_id"`
	SubjectID      string         `json:"subject_id"`
	TopicID        sql.NullString `json:"topic_id"`
	QuestionsCount int64          `json:"questions_count"`
	CorrectCount   int64          `json:"correct_count"`
}

func (q *Queries) CreateExerciseLog(ctx context.Context, arg CreateExerciseLogParams) (ExerciseLog, error) {
	row := q.db.QueryRowContext(ctx, createExerciseLog,
		arg.ID,
		arg.SessionID,
		arg.SubjectID,
		arg.TopicID,
		arg.QuestionsCount,
		arg.CorrectCount,
	)
	var i ExerciseLog
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.SubjectID,
		&i.TopicID,
		&i.QuestionsCount,
		&i.CorrectCount,
		&i.CreatedAt,
	)
	return i, err
}
