// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	CreateCycleItem(ctx context.Context, arg CreateCycleItemParams) (CycleItem, error)
	CreateExerciseLog(ctx context.Context, arg CreateExerciseLogParams) (ExerciseLog, error)
	CreateSessionPause(ctx context.Context, arg CreateSessionPauseParams) (SessionPause, error)
	CreateStudyCycle(ctx context.Context, arg CreateStudyCycleParams) (StudyCycle, error)
	CreateStudySession(ctx context.Context, arg CreateStudySessionParams) (StudySession, error)
	CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error)
	CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCycleItem(ctx context.Context, id string) error
	DeleteExerciseLog(ctx context.Context, id string) error
	DeleteSessionPause(ctx context.Context, id string) error
	DeleteStudyCycle(ctx context.Context, id string) error
	DeleteStudySession(ctx context.Context, id string) error
	DeleteSubject(ctx context.Context, id string) error
	DeleteTopic(ctx context.Context, id string) error
	EndSessionPause(ctx context.Context, arg EndSessionPauseParams) error
	GetAccuracyBySubject(ctx context.Context) ([]GetAccuracyBySubjectRow, error)
	GetAccuracyByTopic(ctx context.Context, subjectID string) ([]GetAccuracyByTopicRow, error)
	GetActiveCycleWithItems(ctx context.Context) ([]GetActiveCycleWithItemsRow, error)
	GetActiveStudyCycle(ctx context.Context) (StudyCycle, error)
	GetActivityHeatmap(ctx context.Context, daysCount string) ([]GetActivityHeatmapRow, error)
	GetCycleItem(ctx context.Context, id string) (CycleItem, error)
	GetExerciseLog(ctx context.Context, id string) (ExerciseLog, error)
	GetOpenSession(ctx context.Context) (GetOpenSessionRow, error)
	GetSessionPause(ctx context.Context, id string) (SessionPause, error)
	GetStudyCycle(ctx context.Context, id string) (StudyCycle, error)
	GetStudySession(ctx context.Context, id string) (StudySession, error)
	GetSubject(ctx context.Context, id string) (Subject, error)
	// Analytics Queries for Study App
	GetTimeReportBySubject(ctx context.Context, arg GetTimeReportBySubjectParams) ([]GetTimeReportBySubjectRow, error)
	GetTopic(ctx context.Context, id string) (Topic, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListCycleItems(ctx context.Context, cycleID string) ([]CycleItem, error)
	ListSubjects(ctx context.Context) ([]Subject, error)
	ListTopicsBySubject(ctx context.Context, subjectID string) ([]Topic, error)
	UpdateCycleItem(ctx context.Context, arg UpdateCycleItemParams) error
	UpdateSessionDuration(ctx context.Context, arg UpdateSessionDurationParams) error
	UpdateStudyCycle(ctx context.Context, arg UpdateStudyCycleParams) error
	UpdateSubject(ctx context.Context, arg UpdateSubjectParams) error
	UpdateTopic(ctx context.Context, arg UpdateTopicParams) error
}

var _ Querier = (*Queries)(nil)
