// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_pauses.sql

package database

import (
	"context"
	"database/sql"
)

const createSessionPause = `-- name: CreateSessionPause :one
INSERT INTO session_pauses (id, session_id, started_at)
VALUES (?, ?, ?)
RETURNING id, session_id, started_at, ended_at, duration_seconds
`

type CreateSessionPauseParams struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	StartedAt string `json:"started_at"`
}

func (q *Queries) CreateSessionPause(ctx context.Context, arg CreateSessionPauseParams) (SessionPause, error) {
	row := q.db.QueryRowContext(ctx, createSessionPause, arg.ID, arg.SessionID, arg.StartedAt)
	var i SessionPause
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSeconds,
	)
	return i, err
}

const deleteSessionPause = `-- name: DeleteSessionPause :exec
DELETE FROM session_pauses
WHERE id = ?
`

func (q *Queries) DeleteSessionPause(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionPause, id)
	return err
}

const endSessionPause = `-- name: EndSessionPause :exec
UPDATE session_pauses
SET ended_at = ?
WHERE id = ?
`

type EndSessionPauseParams struct {
	EndedAt sql.NullString `json:"ended_at"`
	ID      string         `json:"id"`
}

func (q *Queries) EndSessionPause(ctx context.Context, arg EndSessionPauseParams) error {
	_, err := q.db.ExecContext(ctx, endSessionPause, arg.EndedAt, arg.ID)
	return err
}

const getSessionPause = `-- name: GetSessionPause :one
SELECT id, session_id, started_at, ended_at, duration_seconds FROM session_pauses
WHERE id = ?
`

func (q *Queries) GetSessionPause(ctx context.Context, id string) (SessionPause, error) {
	row := q.db.QueryRowContext(ctx, getSessionPause, id)
	var i SessionPause
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSeconds,
	)
	return i, err
}
