// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: study_sessions.sql

package database

import (
	"context"
	"database/sql"
)

const createStudySession = `-- name: CreateStudySession :one
INSERT INTO study_sessions (id, subject_id, cycle_item_id, started_at)
VALUES (?, ?, ?, ?)
RETURNING id, subject_id, cycle_item_id, started_at, finished_at, gross_duration_seconds, net_duration_seconds, notes, created_at, updated_at
`

type CreateStudySessionParams struct {
	ID          string         `json:"id"`
	SubjectID   string         `json:"subject_id"`
	CycleItemID sql.NullString `json:"cycle_item_id"`
	StartedAt   string         `json:"started_at"`
}

func (q *Queries) CreateStudySession(ctx context.Context, arg CreateStudySessionParams) (StudySession, error) {
	row := q.db.QueryRowContext(ctx, createStudySession,
		arg.ID,
		arg.SubjectID,
		arg.CycleItemID,
		arg.StartedAt,
	)
	var i StudySession
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.CycleItemID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.GrossDurationSeconds,
		&i.NetDurationSeconds,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSessionDuration = `-- name: UpdateSessionDuration :exec
UPDATE study_sessions
SET finished_at = ?, gross_duration_seconds = ?, net_duration_seconds = ?, notes = ?
WHERE id = ?
`

type UpdateSessionDurationParams struct {
	FinishedAt           sql.NullString `json:"finished_at"`
	GrossDurationSeconds sql.NullInt64  `json:"gross_duration_seconds"`
	NetDurationSeconds   sql.NullInt64  `json:"net_duration_seconds"`
	Notes                sql.NullString `json:"notes"`
	ID                   string         `json:"id"`
}

func (q *Queries) UpdateSessionDuration(ctx context.Context, arg UpdateSessionDurationParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionDuration,
		arg.FinishedAt,
		arg.GrossDurationSeconds,
		arg.NetDurationSeconds,
		arg.Notes,
		arg.ID,
	)
	return err
}
