// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: study_cycles.sql

package database

import (
	"context"
	"database/sql"
)

const createStudyCycle = `-- name: CreateStudyCycle :one
INSERT INTO study_cycles (id, name, description, is_active)
VALUES (?, ?, ?, ?)
RETURNING id, name, description, is_active, created_at, updated_at, deleted_at
`

type CreateStudyCycleParams struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	IsActive    sql.NullInt64  `json:"is_active"`
}

func (q *Queries) CreateStudyCycle(ctx context.Context, arg CreateStudyCycleParams) (StudyCycle, error) {
	row := q.db.QueryRowContext(ctx, createStudyCycle,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IsActive,
	)
	var i StudyCycle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteStudyCycle = `-- name: DeleteStudyCycle :exec
UPDATE study_cycles
SET deleted_at = datetime('now')
WHERE id = ?
`

func (q *Queries) DeleteStudyCycle(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteStudyCycle, id)
	return err
}

const getActiveCycleWithItems = `-- name: GetActiveCycleWithItems :many
SELECT 
    ci.id AS cycle_item_id,
    ci.order_index,
    ci.planned_duration_minutes,
    s.id AS subject_id,
    s.name AS subject_name,
    s.color_hex
FROM cycle_items ci
JOIN study_cycles sc ON ci.cycle_id = sc.id
JOIN subjects s ON ci.subject_id = s.id
WHERE sc.is_active = 1 
  AND sc.deleted_at IS NULL
ORDER BY ci.order_index ASC
`

type GetActiveCycleWithItemsRow struct {
	CycleItemID            string         `json:"cycle_item_id"`
	OrderIndex             int64          `json:"order_index"`
	PlannedDurationMinutes sql.NullInt64  `json:"planned_duration_minutes"`
	SubjectID              string         `json:"subject_id"`
	SubjectName            string         `json:"subject_name"`
	ColorHex               sql.NullString `json:"color_hex"`
}

func (q *Queries) GetActiveCycleWithItems(ctx context.Context) ([]GetActiveCycleWithItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveCycleWithItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveCycleWithItemsRow
	for rows.Next() {
		var i GetActiveCycleWithItemsRow
		if err := rows.Scan(
			&i.CycleItemID,
			&i.OrderIndex,
			&i.PlannedDurationMinutes,
			&i.SubjectID,
			&i.SubjectName,
			&i.ColorHex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveStudyCycle = `-- name: GetActiveStudyCycle :one
SELECT id, name, description, is_active, created_at, updated_at, deleted_at FROM study_cycles
WHERE is_active = 1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetActiveStudyCycle(ctx context.Context) (StudyCycle, error) {
	row := q.db.QueryRowContext(ctx, getActiveStudyCycle)
	var i StudyCycle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getStudyCycle = `-- name: GetStudyCycle :one
SELECT id, name, description, is_active, created_at, updated_at, deleted_at FROM study_cycles
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetStudyCycle(ctx context.Context, id string) (StudyCycle, error) {
	row := q.db.QueryRowContext(ctx, getStudyCycle, id)
	var i StudyCycle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateStudyCycle = `-- name: UpdateStudyCycle :exec
UPDATE study_cycles
SET name = ?, description = ?, is_active = ?, updated_at = datetime('now')
WHERE id = ? AND deleted_at IS NULL
`

type UpdateStudyCycleParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	IsActive    sql.NullInt64  `json:"is_active"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateStudyCycle(ctx context.Context, arg UpdateStudyCycleParams) error {
	_, err := q.db.ExecContext(ctx, updateStudyCycle,
		arg.Name,
		arg.Description,
		arg.IsActive,
		arg.ID,
	)
	return err
}
