// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: study_cycles.sql

package database

import (
	"context"
	"database/sql"
)

const createStudyCycle = `-- name: CreateStudyCycle :one
INSERT INTO study_cycles (id, name, description, is_active)
VALUES (?, ?, ?, ?)
RETURNING id, name, description, is_active, created_at, updated_at, deleted_at
`

type CreateStudyCycleParams struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	IsActive    sql.NullInt64  `json:"is_active"`
}

func (q *Queries) CreateStudyCycle(ctx context.Context, arg CreateStudyCycleParams) (StudyCycle, error) {
	row := q.db.QueryRowContext(ctx, createStudyCycle,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IsActive,
	)
	var i StudyCycle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActiveStudyCycle = `-- name: GetActiveStudyCycle :one
SELECT id, name, description, is_active, created_at, updated_at, deleted_at FROM study_cycles
WHERE is_active = 1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetActiveStudyCycle(ctx context.Context) (StudyCycle, error) {
	row := q.db.QueryRowContext(ctx, getActiveStudyCycle)
	var i StudyCycle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
