// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: study.sql

package database

import (
	"context"
	"database/sql"
)

const createCycleItem = `-- name: CreateCycleItem :one
INSERT INTO cycle_items (id, cycle_id, subject_id, order_index, planned_duration_minutes)
VALUES (?, ?, ?, ?, ?)
RETURNING id, cycle_id, subject_id, order_index, planned_duration_minutes, created_at, updated_at
`

type CreateCycleItemParams struct {
	ID                     string        `json:"id"`
	CycleID                string        `json:"cycle_id"`
	SubjectID              string        `json:"subject_id"`
	OrderIndex             int64         `json:"order_index"`
	PlannedDurationMinutes sql.NullInt64 `json:"planned_duration_minutes"`
}

func (q *Queries) CreateCycleItem(ctx context.Context, arg CreateCycleItemParams) (CycleItem, error) {
	row := q.db.QueryRowContext(ctx, createCycleItem,
		arg.ID,
		arg.CycleID,
		arg.SubjectID,
		arg.OrderIndex,
		arg.PlannedDurationMinutes,
	)
	var i CycleItem
	err := row.Scan(
		&i.ID,
		&i.CycleID,
		&i.SubjectID,
		&i.OrderIndex,
		&i.PlannedDurationMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createExerciseLog = `-- name: CreateExerciseLog :one
INSERT INTO exercise_logs (id, session_id, subject_id, topic_id, questions_count, correct_count)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, session_id, subject_id, topic_id, questions_count, correct_count, created_at
`

type CreateExerciseLogParams struct {
	ID             string         `json:"id"`
	SessionID      sql.NullString `json:"session_id"`
	SubjectID      string         `json:"subject_id"`
	TopicID        sql.NullString `json:"topic_id"`
	QuestionsCount int64          `json:"questions_count"`
	CorrectCount   int64          `json:"correct_count"`
}

func (q *Queries) CreateExerciseLog(ctx context.Context, arg CreateExerciseLogParams) (ExerciseLog, error) {
	row := q.db.QueryRowContext(ctx, createExerciseLog,
		arg.ID,
		arg.SessionID,
		arg.SubjectID,
		arg.TopicID,
		arg.QuestionsCount,
		arg.CorrectCount,
	)
	var i ExerciseLog
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.SubjectID,
		&i.TopicID,
		&i.QuestionsCount,
		&i.CorrectCount,
		&i.CreatedAt,
	)
	return i, err
}

const createSessionPause = `-- name: CreateSessionPause :one
INSERT INTO session_pauses (id, session_id, started_at)
VALUES (?, ?, ?)
RETURNING id, session_id, started_at, ended_at, duration_seconds
`

type CreateSessionPauseParams struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	StartedAt string `json:"started_at"`
}

func (q *Queries) CreateSessionPause(ctx context.Context, arg CreateSessionPauseParams) (SessionPause, error) {
	row := q.db.QueryRowContext(ctx, createSessionPause, arg.ID, arg.SessionID, arg.StartedAt)
	var i SessionPause
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSeconds,
	)
	return i, err
}

const createStudyCycle = `-- name: CreateStudyCycle :one
INSERT INTO study_cycles (id, name, description, is_active)
VALUES (?, ?, ?, ?)
RETURNING id, name, description, is_active, created_at, updated_at, deleted_at
`

type CreateStudyCycleParams struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	IsActive    sql.NullInt64  `json:"is_active"`
}

func (q *Queries) CreateStudyCycle(ctx context.Context, arg CreateStudyCycleParams) (StudyCycle, error) {
	row := q.db.QueryRowContext(ctx, createStudyCycle,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IsActive,
	)
	var i StudyCycle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createStudySession = `-- name: CreateStudySession :one
INSERT INTO study_sessions (id, subject_id, cycle_item_id, started_at)
VALUES (?, ?, ?, ?)
RETURNING id, subject_id, cycle_item_id, started_at, finished_at, gross_duration_seconds, net_duration_seconds, notes, created_at, updated_at
`

type CreateStudySessionParams struct {
	ID          string         `json:"id"`
	SubjectID   string         `json:"subject_id"`
	CycleItemID sql.NullString `json:"cycle_item_id"`
	StartedAt   string         `json:"started_at"`
}

func (q *Queries) CreateStudySession(ctx context.Context, arg CreateStudySessionParams) (StudySession, error) {
	row := q.db.QueryRowContext(ctx, createStudySession,
		arg.ID,
		arg.SubjectID,
		arg.CycleItemID,
		arg.StartedAt,
	)
	var i StudySession
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.CycleItemID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.GrossDurationSeconds,
		&i.NetDurationSeconds,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubject = `-- name: CreateSubject :one
INSERT INTO subjects (id, name, color_hex)
VALUES (?, ?, ?)
RETURNING id, name, color_hex, created_at, updated_at, deleted_at
`

type CreateSubjectParams struct {
	ID       string         `json:"id"`
	Name     string         `json:"name"`
	ColorHex sql.NullString `json:"color_hex"`
}

func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error) {
	row := q.db.QueryRowContext(ctx, createSubject, arg.ID, arg.Name, arg.ColorHex)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ColorHex,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createTopic = `-- name: CreateTopic :one
INSERT INTO topics (id, subject_id, name)
VALUES (?, ?, ?)
RETURNING id, subject_id, name, created_at, updated_at, deleted_at
`

type CreateTopicParams struct {
	ID        string `json:"id"`
	SubjectID string `json:"subject_id"`
	Name      string `json:"name"`
}

func (q *Queries) CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error) {
	row := q.db.QueryRowContext(ctx, createTopic, arg.ID, arg.SubjectID, arg.Name)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const endSessionPause = `-- name: EndSessionPause :exec
UPDATE session_pauses
SET ended_at = ?
WHERE id = ?
`

type EndSessionPauseParams struct {
	EndedAt sql.NullString `json:"ended_at"`
	ID      string         `json:"id"`
}

func (q *Queries) EndSessionPause(ctx context.Context, arg EndSessionPauseParams) error {
	_, err := q.db.ExecContext(ctx, endSessionPause, arg.EndedAt, arg.ID)
	return err
}

const getActiveStudyCycle = `-- name: GetActiveStudyCycle :one
SELECT id, name, description, is_active, created_at, updated_at, deleted_at FROM study_cycles
WHERE is_active = 1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetActiveStudyCycle(ctx context.Context) (StudyCycle, error) {
	row := q.db.QueryRowContext(ctx, getActiveStudyCycle)
	var i StudyCycle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCycleItems = `-- name: ListCycleItems :many
SELECT id, cycle_id, subject_id, order_index, planned_duration_minutes, created_at, updated_at FROM cycle_items
WHERE cycle_id = ?
ORDER BY order_index
`

func (q *Queries) ListCycleItems(ctx context.Context, cycleID string) ([]CycleItem, error) {
	rows, err := q.db.QueryContext(ctx, listCycleItems, cycleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CycleItem
	for rows.Next() {
		var i CycleItem
		if err := rows.Scan(
			&i.ID,
			&i.CycleID,
			&i.SubjectID,
			&i.OrderIndex,
			&i.PlannedDurationMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubjects = `-- name: ListSubjects :many
SELECT id, name, color_hex, created_at, updated_at, deleted_at FROM subjects
WHERE deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListSubjects(ctx context.Context) ([]Subject, error) {
	rows, err := q.db.QueryContext(ctx, listSubjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subject
	for rows.Next() {
		var i Subject
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ColorHex,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopicsBySubject = `-- name: ListTopicsBySubject :many
SELECT id, subject_id, name, created_at, updated_at, deleted_at FROM topics
WHERE subject_id = ? AND deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListTopicsBySubject(ctx context.Context, subjectID string) ([]Topic, error) {
	rows, err := q.db.QueryContext(ctx, listTopicsBySubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Topic
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionDuration = `-- name: UpdateSessionDuration :exec
UPDATE study_sessions
SET finished_at = ?, gross_duration_seconds = ?, net_duration_seconds = ?, notes = ?
WHERE id = ?
`

type UpdateSessionDurationParams struct {
	FinishedAt           sql.NullString `json:"finished_at"`
	GrossDurationSeconds sql.NullInt64  `json:"gross_duration_seconds"`
	NetDurationSeconds   sql.NullInt64  `json:"net_duration_seconds"`
	Notes                sql.NullString `json:"notes"`
	ID                   string         `json:"id"`
}

func (q *Queries) UpdateSessionDuration(ctx context.Context, arg UpdateSessionDurationParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionDuration,
		arg.FinishedAt,
		arg.GrossDurationSeconds,
		arg.NetDurationSeconds,
		arg.Notes,
		arg.ID,
	)
	return err
}
