// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subjects.sql

package database

import (
	"context"
	"database/sql"
)

const createSubject = `-- name: CreateSubject :one
INSERT INTO subjects (id, user_id, name, color_hex)
VALUES (?, ?, ?, ?)
RETURNING id, name, color_hex, created_at, updated_at, deleted_at, user_id
`

type CreateSubjectParams struct {
	ID       string         `json:"id"`
	UserID   string         `json:"user_id"`
	Name     string         `json:"name"`
	ColorHex sql.NullString `json:"color_hex"`
}

func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error) {
	row := q.db.QueryRowContext(ctx, createSubject,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.ColorHex,
	)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ColorHex,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserID,
	)
	return i, err
}

const deleteSubject = `-- name: DeleteSubject :exec
UPDATE subjects
SET deleted_at = datetime('now')
WHERE id = ? AND user_id = ?
`

type DeleteSubjectParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteSubject(ctx context.Context, arg DeleteSubjectParams) error {
	_, err := q.db.ExecContext(ctx, deleteSubject, arg.ID, arg.UserID)
	return err
}

const getSubject = `-- name: GetSubject :one
SELECT id, name, color_hex, created_at, updated_at, deleted_at, user_id FROM subjects
WHERE id = ? AND user_id = ? AND deleted_at IS NULL
`

type GetSubjectParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetSubject(ctx context.Context, arg GetSubjectParams) (Subject, error) {
	row := q.db.QueryRowContext(ctx, getSubject, arg.ID, arg.UserID)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ColorHex,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserID,
	)
	return i, err
}

const listSubjects = `-- name: ListSubjects :many
SELECT id, name, color_hex, created_at, updated_at, deleted_at, user_id FROM subjects
WHERE user_id = ? AND deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListSubjects(ctx context.Context, userID string) ([]Subject, error) {
	rows, err := q.db.QueryContext(ctx, listSubjects, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subject
	for rows.Next() {
		var i Subject
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ColorHex,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubject = `-- name: UpdateSubject :exec
UPDATE subjects
SET name = ?, color_hex = ?, updated_at = datetime('now')
WHERE id = ? AND user_id = ? AND deleted_at IS NULL
`

type UpdateSubjectParams struct {
	Name     string         `json:"name"`
	ColorHex sql.NullString `json:"color_hex"`
	ID       string         `json:"id"`
	UserID   string         `json:"user_id"`
}

func (q *Queries) UpdateSubject(ctx context.Context, arg UpdateSubjectParams) error {
	_, err := q.db.ExecContext(ctx, updateSubject,
		arg.Name,
		arg.ColorHex,
		arg.ID,
		arg.UserID,
	)
	return err
}
