// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subjects.sql

package database

import (
	"context"
	"database/sql"
)

const createSubject = `-- name: CreateSubject :one
INSERT INTO subjects (id, name, color_hex)
VALUES (?, ?, ?)
RETURNING id, name, color_hex, created_at, updated_at, deleted_at
`

type CreateSubjectParams struct {
	ID       string         `json:"id"`
	Name     string         `json:"name"`
	ColorHex sql.NullString `json:"color_hex"`
}

func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error) {
	row := q.db.QueryRowContext(ctx, createSubject, arg.ID, arg.Name, arg.ColorHex)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ColorHex,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listSubjects = `-- name: ListSubjects :many
SELECT id, name, color_hex, created_at, updated_at, deleted_at FROM subjects
WHERE deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListSubjects(ctx context.Context) ([]Subject, error) {
	rows, err := q.db.QueryContext(ctx, listSubjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subject
	for rows.Next() {
		var i Subject
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ColorHex,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
