// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: topics.sql

package database

import (
	"context"
)

const createTopic = `-- name: CreateTopic :one
INSERT INTO topics (id, subject_id, name)
VALUES (?, ?, ?)
RETURNING id, subject_id, name, created_at, updated_at, deleted_at
`

type CreateTopicParams struct {
	ID        string `json:"id"`
	SubjectID string `json:"subject_id"`
	Name      string `json:"name"`
}

func (q *Queries) CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error) {
	row := q.db.QueryRowContext(ctx, createTopic, arg.ID, arg.SubjectID, arg.Name)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTopicsBySubject = `-- name: ListTopicsBySubject :many
SELECT id, subject_id, name, created_at, updated_at, deleted_at FROM topics
WHERE subject_id = ? AND deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListTopicsBySubject(ctx context.Context, subjectID string) ([]Topic, error) {
	rows, err := q.db.QueryContext(ctx, listTopicsBySubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Topic
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
