// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: topics.sql

package database

import (
	"context"
)

const createTopic = `-- name: CreateTopic :one
INSERT INTO topics (id, subject_id, name)
VALUES (?, ?, ?)
RETURNING id, subject_id, name, created_at, updated_at, deleted_at
`

type CreateTopicParams struct {
	ID        string `json:"id"`
	SubjectID string `json:"subject_id"`
	Name      string `json:"name"`
}

func (q *Queries) CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error) {
	row := q.db.QueryRowContext(ctx, createTopic, arg.ID, arg.SubjectID, arg.Name)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteTopic = `-- name: DeleteTopic :exec
UPDATE topics
SET deleted_at = datetime('now')
WHERE id = ?
`

func (q *Queries) DeleteTopic(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTopic, id)
	return err
}

const getTopic = `-- name: GetTopic :one
SELECT id, subject_id, name, created_at, updated_at, deleted_at FROM topics
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetTopic(ctx context.Context, id string) (Topic, error) {
	row := q.db.QueryRowContext(ctx, getTopic, id)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTopicsBySubject = `-- name: ListTopicsBySubject :many
SELECT id, subject_id, name, created_at, updated_at, deleted_at FROM topics
WHERE subject_id = ? AND deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListTopicsBySubject(ctx context.Context, subjectID string) ([]Topic, error) {
	rows, err := q.db.QueryContext(ctx, listTopicsBySubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Topic
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTopic = `-- name: UpdateTopic :exec
UPDATE topics
SET name = ?, updated_at = datetime('now')
WHERE id = ? AND deleted_at IS NULL
`

type UpdateTopicParams struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateTopic(ctx context.Context, arg UpdateTopicParams) error {
	_, err := q.db.ExecContext(ctx, updateTopic, arg.Name, arg.ID)
	return err
}
